id = "inline_color_previews"
name = "Inline Color Previews for RGB/HEX colors"
version = "0.0.1"
schema_version = 1
authors = ["Erik Eros <erikeros.ev@gmail.com>"]
description = ""
repository = "https://github.com/erikerosev/zed_ext_inline_color_previews"
